### ISSUE TITLE
"Warning: count()" with PHP Version 7.2.7

### ISSUE THREAD

**Issue by kbreynck** [rolandtoth/PageimageRemoveVariations#1]
This module causes a Warning message on my installation with PHP Version 7.2.7

Warning: count(): Parameter must be an array or an object that implements Countable in .../site/assets/cache/FileCompiler/site/modules/PageimageRemoveVariations/PageimageRemoveVariationsConfig.php on line 148

This issue looks similar to this:
https://github.com/processwire/processwire-issues/issues/408

Could you please fix it?

**Comment by rolandtoth** [comment]
Could you check replacing count() with wireCount() on that line and see if everything works as expected? I don't see the error but according the issue you have linked this would fix it.

**Comment by kbreynck** [comment]
Replacing count() with wireCount() fixes this issue.
